@startuml Configuration

class ApplicationConfiguration {
    char *ssid
    char *passphrase
    long idleTimeoutBeforeShutdownInMilliseconds
    long timeoutBetweenHttpRequestsInMilliseconds
}

class BlindConfiguration {
    unsigned int id
    unsigned int buttonPositionX
    unsigned int buttonPositionY
    unsigned int buttonWidth
    unsigned int buttonHeight
    const char* iP
    bool canTilt
    float tiltPositionInPercent
}

@enduml