@startuml Blind Configuration

class Rectangle {
    Point bottomLeftCorner
    float height 
    float width
}

class Point {
    float x
    float y
}

class BlindConfig {
    int level
    Rectangle layout
    int uniqueId
    String ip
    int position
}

@enduml