@startuml Chall Chain Move Blinds

skinparam ComponentStyle rectangle

[HMI] #LightGreen
[BlindsManager] #Yellow
[BlindsAccess] #Grey
[DeviceDataAccess] #Grey
[HttpClient] #LightBlue
database DeviceData #LightBlue

HMI --> BlindsManager
BlindsManager --> BlindsAccess
BlindsManager --> DeviceDataAccess
BlindsAccess --> HttpClient
DeviceDataAccess --> DeviceData

@enduml