@startuml Call Chain Enable and Disable Blinds

skinparam ComponentStyle rectangle

[HMI] #LightGreen
[BlindsManager] #Yellow
[DeviceDataAccess] #Grey
database DeviceData #LightBlue

HMI --> BlindsManager
BlindsManager --> DeviceDataAccess
DeviceDataAccess --> DeviceData

@enduml