@startuml Chall Chain Move Blinds

skinparam ComponentStyle rectangle

[HMI] #LightGreen
[BlindsManager] #Yellow
[BlindsAccess] #Grey
[DeviceAccess] #Grey
[RESTClient] #LightBlue
[Device] #LightBlue

HMI --> BlindsManager
BlindsManager --> BlindsAccess
BlindsManager --> DeviceAccess
BlindsAccess --> RESTClient
DeviceAccess --> Device

@enduml