@startuml Contracts

interface IDeviceStatusContract {
    void enable(String deviceID)
    void disable(String deviceID)
    bool isEnabled(String deviceId)
}

interface IBlindCommandsContract {
    void open(String blindID)
    void close(String blindID)
    void stop(String blindID)
    void goToPosition(String blindID)
}

interface IDeviceContract {
    int getBatteryWarningLevel()
    int getBatteryLevelInPercent()
    void connectWifi(String ssid, String password)
    void powerDown(int timeoutInMilliSeconds)
}

@enduml