@startuml Contracts

interface IBlind {
    unsigned int getId()
    void open()
    void close()
    void stop()
    void tilt()
}

interface IBlinds {
    void open(unsigned int id)
    void close(unsigned int id)
    void stop(unsigned int id)
    void tilt(unsigned int id)
}

interface IDevice {
    void connectWiFi()
    bool isWiFiConnected()
    void powerOff()
    float getBatteryLevelInPercent()
    unsigned int getBatteryWarningLevel()
}

interface IDeviceData {
    void saveBool(const char* key, bool value)
    bool loadBool(const char* key)
    bool clear()
    void close()
}

interface IEnablable {
    enable(unsigned int id)
    void disable(unsigned int id)
    bool isEnabled(unsigned int id)
}

interface ILooper {
    void loop()
}

interface IPersistable {
    void save()
}

@enduml