@startuml Static Architecture

skinparam ComponentStyle rectangle

component Frontend {
    [HMI] #LightGreen
}

rectangle Backend {

    component BusinessLogic {
        [DeviceManager] #Yellow
        [BlindsManager] #Yellow   
    }

    component ResourceAccess {
        [DeviceDataAccess] #Grey
        [DeviceAccess] #Grey
        [BlindsAccess] #Grey
    }

    component Resources {
        database DeviceData #LightBlue
        [HttpClient] #LightBlue
        [Device] #LightBlue
    }
}

Frontend -[hidden]d-> BusinessLogic
BusinessLogic --[hidden]d-> ResourceAccess
ResourceAccess --[hidden]d-> Resources

@enduml