@startsalt blinds-view
{+
    [ Tilt] |[ Poff] | [ None] 
      95% |  OK  |  Online     
    {+
        <<blindsselector
        .................................................................................................................................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ......................................................................................................................................XXXXXXXXXX.
        ......................................................................................................................................XXXXXXXXXX.
        ......................................................................................................................................XXXXXXXXXX.
        .XXXXXXXXXX...........................................................................................................................XXXXXXXXXX.
        .XXXXXXXXXX...........................................................................................................................XXXXXXXXXX.
        .XXXXXXXXXX...........................................................................................................................XXXXXXXXXX.
        .XXXXXXXXXX...........................................................................................................................XXXXXXXXXX.
        .XXXXXXXXXX...........................................................................................................................XXXXXXXXXX.
        .XXXXXXXXXX...........................................................................................................................XXXXXXXXXX.
        .XXXXXXXXXX...........................................................................................................................XXXXXXXXXX.
        .XXXXXXXXXX...........................................................................................................................XXXXXXXXXX.
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .XXXXXXXXXX......................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        >>
    } | * | *

    [Open] | [Stop] | [Close]
}
@endsalt