@startsalt
{+
    [<&layers>   ]  | [ <&menu>  ] | [ <&x>  ] 
    [<&wifi>   ]    | [  <&battery-full>  100% ] | *
    

    {+
        <<blindsselector
        .................................................................................................................................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ............................................................................................................................................XXXX.
        ............................................................................................................................................XXXX.
        ............................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        >>
    } | * | *

    [<&caret-top>   ] | [ <&media-pause>  ] | [<&caret-bottom>   ]
}
@endsalt