@startsalt blinds-view
{+
    [<&layers>   ]  | [ <&menu>  ] | [ <&x>  ] 
    <&wifi>       |  Status      |  <&battery-full>  
    
    {+
        <<blindsselector
        .................................................................................................................................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ...........................................XXXXXXXXXXXXXXXXXXXXXXXXXXXX...............XXXXXXXXXXXXXXXXXXXXXXXXXX.................................
        ............................................................................................................................................XXXX.
        ............................................................................................................................................XXXX.
        ............................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX.......................................................................................................................................XXXX.
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .XXXX............................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        .................................................................................................................................................
        >>
    } | * | *

    [<&caret-top>   ] | [ <&media-pause>  ] | [<&caret-bottom>   ]
}
@endsalt