@startuml Static Architecture

skinparam ComponentStyle rectangle

component Client {
    [HMI] #LightGreen
}

component BusinessLogic {
    [DeviceManager] #Yellow
    [BlindsManager] #Yellow   
}

component ResourceAccess {
    [DeviceDataAccess] #Grey
    [DeviceAccess] #Grey
    [BlindsAccess] #Grey
}

component Resources {
    database DeviceData #LightBlue
    [RESTClient] #LightBlue
    [Device] #LightBlue
}

Client -[hidden]d-> BusinessLogic
BusinessLogic --[hidden]d-> ResourceAccess
ResourceAccess --[hidden]d-> Resources

@enduml