name: learn-github-actions
on: [push]
jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd test
      - run: bazelisk build //:tests
      - run: bazelisk test --test_output=all //:tests